// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrjwiayfyaxzfahziwvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyandpYXlmeWF4emZhaHppd3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDk2NTgsImV4cCI6MjA1OTc4NTY1OH0.WzgZ2LN672pWetHvG7YcFoVI_5o00lOq1IjRzmx8S3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);